### ISSUE TITLE
Run "editing_percent_test" ERROR

### ISSUE THREAD

**Issue by xieyunxiao** [Lammlab/Resic#2]
Hello!
I use your tool but it has some ERROR when I run it , could you help me?

The ERROR **warning** is like :

- ERROR:root: -p 12 -m 2 -l 50 -n 3 --chunkmbs 200 --strata --best
- ERROR:root:edit plot failed
- Traceback (most recent call last):
-   File "~/Experiments/forontiers_jupyter/editing_type_count_by_group_plot.py", line 63, in editing_type_count_by_group_plot
-     plt_res, axes = stacked_bar(data,  show_values=True, value_format="{:.3f}",
-   File "~/Experiments/forontiers_jupyter/bar_utils.py", line 39, in stacked_bar
-     ny = len(data[0])
- IndexError: index 0 is out of bounds for axis 0 with size 0
- INFO:root: finished process running <function editing_type_count_by_group_plot at 0x2b5ba537c790>(('~/Sample_1.fastq', {'norep': {'norep'}, 'rep': {'rep'}, 'norep_hyper': {'norep_hyper_C_G', 'norep_hyper_A_T', 'norep_hyper_G_T', 'norep_hyper_A_G', 'norep_hyper_A_C', 'norep_hyper_C_T'}, 'rep_hyper': {'rep_hyper_A_C', 'rep_hyper_G_T', 'rep_hyper_C_G', 'rep_hyper_A_T', 'rep_hyper_C_T', 'rep_hyper_A_G'}}, <Experiments.forontiers_jupyter.directory_structure_definer.DirectoryStructure object at 0x2b5ba4a8d880>, {"('A', 'C')": '#d12325', "('A', 'G')": '#7C00BE', "('A', 'T')": '#55E5D8', "('A', 'N')": '#41C109', "('C', 'A')": '#DEF407', "('C', 'G')": '#9F3A7D', "('C', 'T')": '#3C2C0D', "('C', 'N')": '#089E4C', "('G', 'A')": '#F69804', "('G', 'C')": '#2482BD', "('G', 'T')": '#A0A269', "('G', 'N')": '#CC1D74', "('T', 'A')": '#1DA6CC', "('T', 'C')": '#d6adc6', "('T', 'G')": '#018439', "('T', 'N')": '#3939a7', "('N', 'A')": '#37462a', "('N', 'C')": '#11dacd', "('N', 'G')": '#ab6b5f', "('N', 'T')": '#1eb1cf', 'unchanged': '#1a48a7'}))
- 

It seems that the problem stems from **test_pipe.snp_removal_test** , line 642, in resic_run_file.py.
I don't know where I am doing wrong. Please help me! Thanks!

**Comment by RoniHaas** [comment]
Hi @xieyunxiao, could you please check in your output directory which files have been created up to this point?

_Originally posted by @RoniHaas in https://github.com/Lammlab/Resic/issues/1#issuecomment-1114012056_

**Comment by xieyunxiao** [comment]
@RoniHaas Thank you for your reply! 
The _**snp_removal**_folder provide a 0 Byte file named _**sample_norep_hyper_A_G_snp_removal.pileup**_
Other folders "graph_aligner", "pileup_generation", "no_change", "read_threshold" seem have no problem.

**Comment by RoniHaas** [comment]
Before further investigation: did you remove the headers from the dbSNP file before running?
